//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.14.7.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace MyJetWallet.Fireblocks.Client
{
    public class BaseClient
    {
        private readonly ClientConfigurator _clientConfigurator;

        public BaseClient(ClientConfigurator clientConfigurator)
        {
            this._clientConfigurator = clientConfigurator;
        }

        public string BaseUrl => _clientConfigurator.BaseUrl;
    }
}